[[Glib]]
arch = "aarch64"
git-tree-sha1 = "fd43459d00ad88c3ee4e96841dca7e1dd19915c5"
os = "macos"

    [[Glib.download]]
    sha256 = "a2d1e6300d5fe81c75cf38f764a9cbda9c491ce45cf305108594a5335ee09dc0"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "64bf5a5133f2202b3f5d5ebb4903d401a3f57bf4"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "933d645ed594ad933abe82d94f380e6909ae063c6f9c8f3e421560a43c4d74e4"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "0a9493f26f2ffefee2e2829ea351fe880a17d8fc"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "e8cd53333ea4741b81d26719ce00945b6ccfbf7d227a5ba42f813fe0eb8f947f"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "e391a1488f3d4f829fcc3cd559cea04a649a1634"
os = "freebsd"

    [[Glib.download]]
    sha256 = "2addfb3f007aebdc1b5e615b9c7162fccfd1366f651caabd80349cd1bb8d52a0"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.aarch64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7160ba630fb30043feef2cbbab0e883f9f4cd263"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "48b734f3fb2c0b3e39821edb6aee22969040d786dd36743ccbd3f329afb21bb1"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f3245a6b26cd7704ea240443ff81615c9d7bb1c0"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "2679bb78519dd4d6151faa21882faf2dcce34d62337930893e2f926c36a06d01"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f03c76741fa2943a969ffb52fef09ed7959692c"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "c768e758f07c35d98fdb2eaee9f7b609e3fd6d9c22abb2d01bc6fe344b08b834"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f4d56d9d3bea85f05c31c0cae31a136eb9d383c"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "506f9e9d2c574fe3cc733ce29429aab7a8b1655fa057168614f89dfaea3faea8"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "9bb5fb060de67fb14ff5ffdc87228b299a9864f5"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "278eb4dcc5d85b24cf5c9154f5d0fcae61844d43b768ecf26a61b0ad46c43938"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "130078a8dd67078236b6bb251a7ce5f1077ccee7"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "c241f9a978aafb95fe520da78216996ba2e30aed95900ba58e198242efa54e5e"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "d6ebda0017fbcbdeb1207411b1efe828fbd85227"
os = "windows"

    [[Glib.download]]
    sha256 = "79bb06eadc2903817a1169551498a449fcc99f1c98e00d359d8175befc85b885"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "1b9fa0c490ba29f4972e780d66d92071cce00bd3"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "ff8306c77f5f1f9c7dcdcad1b03b6d2ff5c6e90886e06f3df3ab4a8d99bf9c30"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "riscv64"
git-tree-sha1 = "d9f684bf856a87fb90b331aa629b28735169e073"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "9e36d5d19d3d5220ec9c89869bf751a646fe97b0051df476fe33fed8e21e87bc"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.riscv64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "e6930b0ea8aad6ffdda22e1b025ba63f096e7816"
os = "macos"

    [[Glib.download]]
    sha256 = "95dd6cec08d568bd451d7bec3bab96af9fe250368d4a215ba0958da320c12f4c"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "18dc77c6166dfe4ffcd8ef44d14dc7497745d90c"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "dfecee3cd20fcf9b9b36b6ac47583ed723597828d5c46f807487877b798a78de"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "89411e834ca385e8f5920ae64240662143172ce8"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "f5bdb9f05b254c5554b1e8ee0d44df91e650f11496768c683875c122cde148fc"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "38108b10e1818c49fd5b9b1b4e2b5def3b7ce437"
os = "freebsd"

    [[Glib.download]]
    sha256 = "8809399416960b4b4f5582e76e8c2c72166e0358d2376f4d88be433c0557957e"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "354b612e346f34e9bff779501b1443f6d867bccd"
os = "windows"

    [[Glib.download]]
    sha256 = "af5003fb9997b48febada3e2bd250012dff62282f2bab2d8503a473488d873ff"
    url = "https://github.com/nhz2/Glib_jll.jl/releases/download/Glib-v2.84.3+0/Glib.v2.84.3.x86_64-w64-mingw32.tar.gz"
